[Fix][Environments][Algolia Plugin] SUPP-298 Added safety check so that sync-to-algolia does not appear in an env's model
BuilderIO/builder pull request #2959
Opened 2024-01-27 18:47 UTC by murtaza-builder

Added safety check so that sync-to-algolia button does not appear, in an env's model so that changes of mixup dont arise.

2024-01-30 18:02 UTC, sanyamkamat requested changes

2024-01-30 18:25 UTC, murtaza-builder commented on plugins/algolia/src/plugin.tsx
@shyam-builder Need your thoughts in this specific change. Is it fine if disable syncing models to algolia if we are in an env? Basically somewht disabling plugins from an env.
wdyt?

2024-01-31 05:28 UTC, shyam-builder commented on plugins/algolia/src/plugin.tsx
Is there a reason why we would want to disable? I can see customers wanting to finish translation and all in a lower environment and push it up.

2024-01-31 05:29 UTC, shyam-builder commented on plugins/algolia/src/plugin.tsx
Specifically what breaks from an environment?

2024-01-31 17:02 UTC, murtaza-builder commented on plugins/algolia/package.json
> +  "version": "0.0.6",
done

2024-01-31 17:06 UTC, murtaza-builder commented on plugins/algolia/src/plugin.tsx
If the installation and usage of plugin happens in same env/space its not a problem but if installation is done in main space and the usage (webhook url syncing) is done in env, it messes up the webhook url params. 
Which could lead to confusion and improper working. Happened in SUPP-298.

Thus it would be better if plugins work in main space only

2024-10-07 15:30 UTC, samijaber commented
@murtaza-builder Going over stale PRs: can this one be closed for now? It's still in draft mode

2024-10-08 14:57 UTC, murtaza-builder commented
> @murtaza-builder Going over stale PRs: can this one be closed for now? It's still in draft mode

yes, we can close this for now, will revive it when needed

2024-10-08 14:57 UTC, closed without merging