Remove throttle
BuilderIO/builder pull request #931
Opened 2022-03-08 10:29 UTC by armgjoka

## Description

Fix the bug that data from multiple sources are not displayed. Removed @Throttle, because it was invoking the function once every 100ms and we were missing some calls to the datasources (if two different calls within 100ms, the second one was skipped, hence data missing).

2022-03-08 15:15 UTC, samijaber requested changes
I assume the throttling was there to reduce the number of requests. I don't think we need to completely get rid of it, that might cause a lot more requests than we'd like! Instead, we should fix the throttling logic such that it grabs the latest value within the throttling time window.
I see that we manually wrote `throttle`, so it might be hard to do that. We could dig into alternative libraries that support what I described

2022-03-08 15:18 UTC, samijaber commented
https://lodash.com/docs/#throttle could be one solution to this problem. My guess is that our implementation of the `leading: true` option in our `throttle` function is flawed here. It's meant to grab the last value in the time window, but you said it's not. 🤔

2022-03-08 15:24 UTC, armgjoka commented
@samijaber we want to throttle the requests to an endpoint. How throttle worked here: 
Request1 (1ms), Request2 (30ms), Request3 (110ms). For this case we would miss the Request2 (throttle wait time is 100 ms). While that would be ok for cases all these three requests go to the same endpoint, the issue here is that these three requests go to different endpoints. So to implement that correctly we would have a 100ms throttle window for each endpoint, in this case all three requests would be executed because they are targeting different endpoints.

2022-03-08 20:45 UTC, mrkoreye commented
@steve8708 do you happen to remember what the throttle was solving in this case? Will it cause problems if we remove it?

2022-03-08 20:54 UTC, steve8708 commented
I think it's safe to remove if we test it out and see if normal editing usage doesn't overly hammer these requests, as I think the editor does some throttling too which may do what we need

would also recommend that if we no longer throttle,then we shouldn't have this method called `throttledHandleRequest` that doesn't actually throttle, and instead just refactor those calls to purely do `this.handleRequest` instead

2022-03-09 16:44 UTC, samijaber approved these changes

2022-03-09 16:45 UTC, samijaber commented
Oh, one last thing @armgjoka! Would you be able to add this change to the `CHANGELOG.MD` doc? We're working on a way to automate changelogs very soon, but for now it needs to be done manually.

2022-03-10 13:50 UTC, merged